### ISSUE TITLE
More refined on-reboot screen required

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#106]
When I upgrade my MAZI installation from v2.4.4 to v2.4.6 I am asked to wait for a few minutes, then reboot the MAZI zone.

I click on the admin button to 'reboot' and the MAZI zone reboots. 

It then comes back up and refreshes the web browser page (nice). However, I get this technical looking basic page (see image below).

![inelegant-reboot-message-mazi246](https://user-images.githubusercontent.com/18211485/40914552-8a06bf40-67f0-11e8-8f15-27f183bbebd6.png)

A novice administrator might not know what to do next.

(1) Would it be possible to change this, so on rebooting (once I have upgraded my installation) I get a more friendly screen? Something like: "Congratulations, you have upgraded your MAZI zone. You can now continue. Click on this link to find out what's new, or click on the control panel buttons to make any further manual changes. "

(2) At the moment I have to manually edit the web browser's address bar to go to the default home page. Could the installation process be changed so on reboot after an upgrade, I am pushed to either (a) the default admin home page, or , (b) a custom "welcome" page?

thanks! Mark

**Comment by haniavis** [comment]
Hi Mark,

this screen was not supposed to appear after the upgrade. Probably you didn't wait enough for the update to be finished.

From v2.4.6 and on, the update process is changed in order to avoid this kind of issues. So since v2.4.6 when you click update the raspberry is automatically rebooted and updated and you can connect back to the MAZI Zone only if the update process is finished.
