### ISSUE TITLE
Icons: easier way to enter an icon for an application instance

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#107]
In the very latest version (2.5 updated from 2.4.6 through the admin panel), when I edit an application instance the icon entry disappears and I am not allowed to save my changes without entering an icon, but it is not obvious how to do this.

The ideal solution would be to be able to click on a button and choose an icon, but until this is implemented I think it is urgent to solve the above problem because it blocks very important admin actions like setting a default etherpad page.

As a quick solution, I would make "optional" the icon field with a "default" icon used when there is no choice.

**Comment by panosnethood** [comment]
Hi, I saw that this is not corrected in v2.5.2 but I consider it an important bug because it makes very difficult to carry out one of the main operations of the administrator (editing an application instance). 

I would not release a new stable version without this being resolved.

**Comment by haniavis** [comment]
Hi, we have created a new page in the wiki for editing the application icons https://github.com/mazi-project/guides/wiki/Administrator-icons

In the next version the icon will not be obligatory and there will be a hint with a link to the wiki page.

**Comment by mgaved** [comment]
Does the MAZIzone hold the whole set of icons from Font Awesome? (that would be awesome...)

Could there be a link, so when you click on the "Icon" word in the pop up window it shows a view of the directory where the files are kept and the administrator could click on a selection, which is then made the chosen Icon. 

I would prefer some means where the administrator can preview the potential items, and ideally, the selection is then auto-typed into the window, rather than having to go online to look at the icons, as there are situations where people are configuring MAZIzones where they do not have access to the internet.

Thanks for coming up wit ha route to a large number of icons!

**Comment by panosnethood** [comment]
Thanks for correcting this. I guess what Mark proposes could be a nice enhancement, but I would not label it as a "bug" anymore.

**Comment by mgaved** [comment]
Hi - Iam finding some issues with changing the icons when creating a new instance of Etherpad: when I go to change them to something from font- awesome (e.g. https://fontawesome.com/icons/cloud-sun?style=solid) , it keeps reverting to fa-5x

**Comment by haniavis** [comment]
The font-awesome library is updated since v3.0 so this can be closed
