### ISSUE TITLE
On update, change version number of MAZI shown in admin interface

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#125]
I have a MAZI zone v2.5.3. I go into dual mode and Check for Updates. It tells me that there is an update available. I click on Update. The MAZIzone restarts (presumably with the new update). I go into the MAZI Administration interface. In the bottom left hand side of the screen the version number of the MAZIzone is shown. It is still V2.5.3. I have done an update, yet the version number of my MAZI installation has not changed.

**Recommendation:** When an admin user updates their MAZIzone, indicate this has happened by changing the version number of their installation. 

I think if I am on v2.5.3 and I do an update, the version number of the installed system should change (to v2.5.4, or perhaps v2.6, or even v3). There should be some indication changes have taken place.

Thanks! 

![v253-update-available](https://user-images.githubusercontent.com/18211485/43198906-2f328c26-9008-11e8-8a9e-eaafc4910cf3.png)

**Comment by haniavis** [comment]
Hi,

MAZI portal is part of the TranslateWiki open source community https://translatewiki.net/wiki/Translating:MAZI_Toolkit and is being translated to multiple languages.

So whenever there are updates on a language, they are being sent to our repository. These are the updates you got and that's why you didn't see a new version number. You only got some new translations to new languages.

We always mention [here](https://github.com/mazi-project/guides/wiki/Version-History)  updates and new releases.

**Comment by mgaved** [comment]
Thanks - this is useful to know. Can I suggest this information is built into the documentation held on the MAZI toolkit? (for the benefit of administrators who only have occasional internet access)
cheers!
