### ISSUE TITLE
No switch device with OpenWrt router

### ISSUE THREAD

**Issue by juliobrome** [mazi-project/portal#129]
Hello i have a gl-i AR300M16 with openwrt pre-installed (LEDE Reboot 17.01.4 r3560-79f57e422d and other softwares) and a mazizone (2.5.3) and i can't activate the switch device. I don't understand why, i follow the guide but it's too short for troubleshouting.
Is somebody have already connected an external router OpenWrt and can explain me how to do that ?
Do i re-flash my router with an other Version of OpenWrt ?
Help... :)

**Comment by panosnethood** [comment]
Hi Juliobrome,

Thanks for bringing our attention to this feature. The truth is that although the basic functionality is implemented, we have not tested it thoroughly. 

When it was first introduced I had managed to make it work with the TP-link MR3020 (and wrote a first draft of the guide) but it was slow and didn't use it in practice.

Then other important issues appeared and this has been somehow left behind. I guess the big priority for us right now is to resolve some issues with the integration with nodogsplash and make the transition to stretch and the Raspberry Pi B+. Afterwards, I hope there will be some time to get back to this.

Btw, since you are one of the few "external" to our project users, it would be great to know how you learned about the MAZI toolkit and how you plan to use it.

**Comment by juliobrome** [comment]
Hello, of course, excuse me.
I'm teacher and artist in france, i work with my students on art and network. Sometimes with net art and sometimes on collaborative works and creations. I have a friend in bruxelles who work with pirate box and he tell me to have a look on mazi project for what i want to do. 
I work with constant in bruxelles, it's an artistic group, they use to deploy network with raspberry pi and collaborative tools, but they built it from scratch (they are good :) and i like this approach. So now i try to teach with these tools and i think for begining mazi is good for my plans. It's work great with my raspberry but i have 25-50 students and i need to increase the network power ! At the begining i buy myself the hardware (before the school buy it) but for the moment it's not a sucess... i try an extern antena, not work, i try the tplink 3020, not work, and now the new router GL-i... not work.
best, JB

**Comment by panosnethood** [comment]
Great! Thanks a lot!

I hope that moving to the B+ model will be already an improvement in terms of performance. The smooth integration with more powerful routers running OpenWRT will hopefully follow.

In the mean time feel free to create issues with feature requests, things that can be improved, etc.

**Comment by panosnethood** [comment]
Btw, when I succeeded deploying this set-up as described here: https://github.com/mazi-project/guides/wiki/External-OpenWRT-router, I did it with openwrt-15.05.1-ar71xx-generic-tl-mr3020-v1-squashfs-factory.bin. But the admin panel was very slow perhaps due to some non-optimized functionality and I abandoned it as an option because I work a lot with the admin interface in the workshops I run. 

But perhaps the performance for the "users" is improved. I didn't test it properly to know. If you want you could perhaps try with the older MAZI toolkit v.2: http://nitlab.inf.uth.gr/mazi-img/mazizone-v2.2.zip

In any case, as far as the MR3020 is concerned, the PirateBox is a good way to test its performance limits. For bigger routers, you will need to wait a little ....

**Comment by juliobrome** [comment]
ok i try with this version 2.2 and if i fail a will work with the raspberry alone, i have an external antenna but for the moment i fail to connect it on the pi :/
i have a pi3b+ so when it's ready with mazi i install it on, specs are better than my actual pi3

**Comment by panosnethood** [comment]
Just realized that you have a MR3020 that is not compatible with OpenWRT! 

Unfortunately, this wouldn't work. The libremesh community, https://libremesh.org/, is very active in exploring hardware options that are compatible with OpenWRT. Perhaps you could do some research for devices you can buy today that are "flushable". 

Another option, is to wait for the librerouter, https://librerouter.org/, which will hopefully solve this big problem ....

**Comment by juliobrome** [comment]
Thanks ! I have an other one the glinet ar300m16 ext with OpenWrt but its not work too :( if you have a solution for it :) 

⁣Envoyé par BlueMail ​

Le 13 août 2018 à 22:32, à 22:32, panayotis <notifications@github.com> a écrit:
