### ISSUE TITLE
How can I do a Mazi setup from zero?

### ISSUE THREAD

**Issue by nicopace** [mazi-project/portal#39]
Hi Guys,

My name is Nicolas Pace, I'm part of the LibreMesh project, and we want to collaborate with your project.
I would like to start by creating a Mazi image from scratch to understand the process and all the moving parts.
Do you have a script that installs everything? or is there a set of guides that helps creating an image based on a barebone raspbian image?

Thanks in advance!

**Comment by panosnethood** [comment]
Hi Nicolas, thanks a lot for your interest! It would be great to collaborate with LibreMesh since the two projects are highly complementary.

At this stage there is not a script but a set of guides: https://github.com/mazi-project/guides 

The main repository is actually what you ask for but it needs some updating to reflect the latest developments. @haniavis could inform you about the schedule on this.

In the wiki of the same repository, https://github.com/mazi-project/guides/wiki, we develop a wider set of guides for different aspects/phases of the toolkit installation and deployment. After we finalize this content, there will be different "representations" of it in different forms (web, printed, etc), as for example the "public facing" guidelines here: http://www.mazizone.eu/toolkit_guidelines/

We will keep you updated :-)

**Comment by nicopace** [comment]
Thanks @panosnethood to reply.
The links you provided me are very useful from the end-user perspective.
I'm looking more for 'how to contribute' or developer guidelines... like how to setup a working development environment... how all this peaces fit together.

Basically, the set of commands you run to build the mazizone-*.zip images available here: http://nitlab.inf.uth.gr/mazi-img/

Thanks!

**Comment by panosnethood** [comment]
OK! For the moment, to make it more concrete, (part of) those commands are listed here:
http://nitlab.inf.uth.gr/mazi-guides/setup.html
http://nitlab.inf.uth.gr/mazi-guides/captive.html

But as I said the technical guidelines (including the above two sections) need updating ... more soon!

**Comment by nicopace** [comment]
Saw those.

Ok... let me know If I can be of any help to test or proofread it :)

**Comment by haniavis** [comment]
Hi @nicopace the MAZI guides for advanced users are now updated to the current version of the toolkit, as you can see here:
http://nitlab.inf.uth.gr/mazi-guides

**Comment by nicopace** [comment]
Great @haniavis thank you very much!!!
