### ISSUE TITLE
QRcode to connect directly to the MAZI Zone AP

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#66]
I wonder if it is possible to use a QR Code that would first connect a device to the MAZI Zone and then redirect it to the local URL?

**Comment by mgaved** [comment]
QR codes can be used to communicate URLs (search the web for "QR code generator", this will point you to a number of tools that will create a QR code for your preferred URL). 

Is your question about whether a URL entered into a smartphone web browser could trigger the smartphone ( / tablet / other device with a QR code reader, web browser, and WiFi)  to set up a WiFi connection to a MAZIzone in the local area?

Or perhaps you're asking if a QR code could hold a script that runs on the device to (1) set up a connection to the local MAZIzone, then (2) launches a web browser then (3) enters the URL for the MAZIzone in the triggered web browser?

If the latter case (running a script on the device/launching web browser/adding URL) then  I would assume you'd need permissions on the device to run scripts that can launch applications. This might be helpful for Android phones: https://developer.android.com/guide/components/intents-common.html#ViewUrl (loading a web page from another application running on the phone).

**Comment by panosnethood** [comment]
Yes, ideally I would like that everything happens automatically :-) 

I understand the security risks but was wandering about the available options and their trade-offs.

Perhaps it would be simpler to have a MAZI app that does all this based on a special way to "recognize" the existence of a MAZI zone in the area. One could even imagine some sort of "certification" infrastructure to make sure that a MAZI Zone is "secure"? 

Not sure at all. I just relayed the question of another person since I think it could arise for other people as well and it is useful to think of ...

**Comment by raot** [comment]
Think of a situation in a public environment where people just walk by. They should not need to pay much attention to MaziZone, just use it, in a way. Hence turing on Wi-Fi, scan for Mazizone, connect, etc. may seem to much of a hassle allready.

Hence I thought of making access to the Mazizone as easy as possible, I came up with the same two steps you allready mentioned.

First, connecting to the MaziZone Wi-Fi by scanning a QR code that is pinned on the wall or displayed on the raspberry's display is the first step.
Second, by scanning another QR code should open a specific webpage of the MaziZone in the phone's browser. 

Of course, if a script can be triggered in the users phone that does both, that would be great, too, taken into account security issues as mentioned already.

The most important issue is that it seems that apple products and android phones behave quite different. QR codes to access Wi-Fi networks can adhere to some "standard", which seems not to be recognized by apple. With android though it worked fine to connect (https://en.wikipedia.org/wiki/QR_code#WiFi_network_login).

In a similar situation it might be useful to do the opposite, too. Present a QR code allready present on the mobile phone to the camera of the raspberry and trigger the display of a webpage specific to that QR code (user id, similar to a login using the QR code instead of an id/password).

**Comment by mgaved** [comment]
Hey raot, I think "the challenge of making MAZIzones visible, and easy to access" is an emerging thread -it's something we've been thinking about in Creeknet. We have been also thinking about low tech methods like posters and signage.

Is the QR code approach something you could build a prototype for that we could then try out? 

In terms of numbers of people who have Android vs. people who have Apple, I believe the numbers are about 80%/ 20% in favour of Android (e.g. https://www.gartner.com/newsroom/id/3609817) , so a solution that works on Android only would connect the majority of people. Plus Android phones tend to be cheaper so we would be achieving our target of a system that is open to a wider part of the population.

p.s. In Creeknet we have a specific need to learn more about QR code reading, perhaps you can help us, we've promised one of the boaters we'd make him a QR code flag which when you took a picture of it, would show a pirate flag on the phone, can you help us do that? :-)

**Comment by haniavis** [comment]
H,
the connection to a MAZI Zone Wi-Fi network through a QR code seems a nice addition that could be implemented easily.

@raot we don't even need a second QR code to open a specific URL, since we have already implemented the captive portal functionality in the toolkit. So as soon as someone would scan the QR code, the user will be connected to the MAZI Zone and a predefined URL would pop-up automatically.

**Comment by raot** [comment]
I have read about the captive portal functionality in the guides, yes, so if I understand the mechanics correctly, that would make the need for a second qr code for the URL obsolete, in deed. However, I could not make the captive portal working with my installation. This is probably due to some customizations I did to the namings (ssid, site name, etc.). Could we have a chat on this so I understand better how to make captive zones work even w/customizations in place?

**Comment by raot** [comment]
@mgaved And the flag thing sounds funny and I try to implement this on my setup.

**Comment by panosnethood** [comment]
Yes, I think we need to review carefully how the automatic redirection works in different scenarios since there seem to exist issues in certain situations. See #67 & #40

**Comment by haniavis** [comment]
This can be closed. 

A QR code for showing the WiFi network and password is automatically created since v2.4.1.

**Comment by haniavis** [comment]
The toolkit automatically creates the QR code for the current WiFi network.

You can find the QR code and perhaps print it to show it to your users in the Network tab of the admin interface, http://demo.mazizone.eu:4567/admin_network
